name: Execute External API with Reviewer Info

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  execute_api:
    runs-on: ubuntu-latest

    steps:
      - name: Get Reviewers
        id: get_reviewers
        run: |
          PR_NUMBER="${{ github.event.pull_request.number }}"
          TOKEN="${{ secrets.GITHUB_TOKEN }}"

      - name: Execute External API with Reviewer Info
        run:
          using: "node16"
          main: "script.js"
