name: Test CI

on:
    push:
        branches:
            - main
            - 'feature/**'
jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js 16.13.1
              uses: actions/setup-node@v3
              with:
                  node-version: '16.13.1'
                  cache: 'npm'
            - run: npm i
            - run: npm test
